# Generated by Django 5.2 on 2025-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='my_email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
