# Generated by Django 5.2 on 2025-04-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_grades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name_plural': 'Grade'},
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='price',
            new_name='price_per_kg',
        ),
    ]
