# Generated by Django 5.2 on 2025-04-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_grades_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name_plural': 'Grades'},
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='grade',
            new_name='name',
        ),
    ]
