# Generated by Django 5.2 on 2025-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grades/'),
        ),
    ]
